// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func ActivityLog(todaysDate string, yesterdaysDate string) templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
			if !templ_7745c5c3_IsBuffer {
				templ_7745c5c3_Buffer = templ.GetBuffer()
				defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("`<!doctype html> <html><head><style>\n            input[type='time']::-webkit-calendar-picker-indicator {\n                filter: invert(1);\n                cursor: pointer;\n                opacity: 1;\n                background-color: #000;\n            }\n        </style></head><body><div class=\"flex flex-col justify-center items-center gap-5 py-5\"><div class=\"text-center mb-5\"><h2 class=\"text-xl font-bold text-gray-900\">Log Activity</h2></div><form class=\"flex flex-col justify-center items-center gap-5 w-full max-w-md\" hx-post=\"/activity-log\" hx-target=\"#feedback\" hx-swap=\"outerHTML\" hx-indicator=\"#indicator\"><label class=\"input input-bordered flex items-center gap-2 w-full bg-white text-gray-900\">Activity <input type=\"text\" class=\"input input-bordered text-gray-900\" name=\"activity\" required></label> <label class=\"input input-bordered flex items-center gap-2 w-full bg-white text-gray-900\">Start Time <input type=\"time\" class=\"input input-bordered text-gray-900\" name=\"start_time\" required></label> <label class=\"input input-bordered flex items-center gap-2 w-full bg-white text-gray-900\">End Time <input type=\"time\" class=\"input input-bordered text-gray-900\" name=\"end_time\" required></label> <label class=\"input input-bordered flex items-center gap-2 w-full bg-white text-gray-900\">Comments <input type=\"text\" class=\"input input-bordered text-gray-900\" name=\"comments\" placeholder=\"optional\"></label> <button type=\"submit\" class=\"btn bg-blue-500 text-white hover:bg-blue-600\">Submit activity</button></form><div id=\"indicator\" class=\"htmx-indicator hidden\"><div class=\"flex justify-center items-center w-full\"><span class=\"loading loading-spinner loading-lg text-primary h-20 w-20\"></span></div></div><div id=\"feedback\" class=\"text-center\"></div></div></body></html>`")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if !templ_7745c5c3_IsBuffer {
				_, templ_7745c5c3_Err = io.Copy(templ_7745c5c3_W, templ_7745c5c3_Buffer)
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = template().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
