// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.648
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func template() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"UTF-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\"><link href=\"https://cdn.jsdelivr.net/npm/daisyui@4.10.1/dist/full.min.css\" rel=\"stylesheet\" type=\"text/css\"><script src=\"https://cdn.tailwindcss.com\"></script><script src=\"https://unpkg.com/htmx.org@1.9.11\" integrity=\"sha384-0gxUXCCR8yv9FM2b+U3FDbsKthCI66oH5IA9fHppQq9DDMHuMauqq1ZHBpJxQ0J0\" crossorigin=\"anonymous\"></script><script src=\"https://unpkg.com/htmx.org@1.9.11/dist/ext/response-targets.js\"></script><style>\n            .main-header {\n                font-family: 'Arial', sans-serif;\n                font-size: 24px;\n                font-weight: bold;\n                color: #000;\n                margin: 20px 0;\n            }\n            .nav-buttons a {\n                margin-right: 10px;\n                padding: 10px 15px;\n                border-radius: 5px;\n                text-decoration: none;\n                color: #fff;\n            }\n        </style></head><body class=\"bg-white text-gray-900\"><div class=\"container mx-auto p-5\"><div class=\"flex justify-between items-center border-b pb-5 mb-5\"><h1 class=\"main-header\">ImproveYourself</h1><div class=\"nav-buttons\"><a href=\"/activity-log\" class=\"bg-gray-600 hover:bg-green-700\">Add Activity</a> <a href=\"/activities-for-day\" class=\"bg-gray-600 hover:bg-blue-700\">Browse Activity</a> <a href=\"/potato-time\" class=\"bg-gray-600 hover:bg-red-700\">Potato Time</a> <a href=\"/dashboard\" class=\"bg-gray-600 hover:bg-purple-700\">Dashboard</a> <a href=\"/settings\" class=\"bg-gray-600 hover:bg-gray-700\">Settings</a> <button hx-post=\"/logout\" class=\"bg-black hover:bg-gray-800\">Logout</button></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
